projectName=piplex
projectGroup=io.github.green4j
projectAuthor=Anatoly Gudkov
projectCopyright=2026 Anatoly Gudkov and others

srcJavaVersion=21

checkstyleVersion=10.26.1
jupiterVersion=5.11.3
junitPlatformVersion=1.11.3

greenJellyVersion=0.1.6
discasVersion=0.0.5
testcontainersVersion=2.0.5

sezpozVersion=1.13
annotationIndexerVersion=1.18

jenkinsVersion=2.568.3
jenkinsBomVersion=7020.vf38cb_40380d1
jpiPluginVersion=0.58.0
