// Announce a completion the producer never announced.
//
// Who this is for: whoever knows whether the data actually exists -- usually not the platform team.
// The producer finished and did not publish: it died between the two, or the record was lost, and
// consumers elsewhere are waiting while the data sits there.
//
// RUN IT ON THE CONTROLLER THAT PRODUCES THIS MILESTONE. Publishing asserts that a particular
// controller finished particular work, so it is written under that controller's own identity:
// there is no operations credential for it, and under a grant per key no other controller is
// granted this milestone at all.
//
// This is not an administrative tick. Consumers trust it exactly as much as they trust the
// producer's own publication, because it is the same assertion. CHECK THAT THE DATA EXISTS FIRST.
// Publishing a round that was not produced starts downstream work on data that is not there.
//
// Generated by piplex-init from the estate description. The block below is the estate; everything
// under it is the procedure, and it is what the tests run. Regenerate rather than editing:
//
//   java -jar piplex-init.jar --from estate.properties
//
// See docs/09-deployment.md.

// ---- piplex-init: generated from the estate. Regenerate rather than editing it. ----
final String ENVIRONMENT = ''
final String OWNER_ID = ''
final List OWNERS = []
final String CREDENTIALS_ID = ''
final String CLIENT_ID = ''
final Map WORK = [:]
// ---- end piplex-init ----

// Ungenerated, this job knows no milestone, and a milestone published to a guessed key cannot be
// taken back.
if (!ENVIRONMENT?.trim() || WORK.isEmpty()) {
    error 'piplex: this job has not been generated. It is the template piplex-init fills in from ' +
          'the estate description -- run that and install what it writes'
}

// Only work that publishes something. The rest has no milestone to announce.
final Map PUBLISHES = [:]
WORK.each { name, work ->
    if (work.completedWhen) {
        PUBLISHES[name] = work
    }
}
if (PUBLISHES.isEmpty()) {
    error 'piplex: no work in this estate publishes a milestone, so there is nothing here to ' +
          'announce. Name one in completedWhen and regenerate'
}

properties([
        parameters([
                choice(name: 'WORK', choices: PUBLISHES.keySet() as List,
                        description: 'Which work finished. Its milestone is the key published'),
                string(name: 'GENERATION', defaultValue: '',
                        description: 'The round that is complete, usually the business date'),
                booleanParam(name: 'DATA_CONFIRMED', defaultValue: false,
                        description: 'Tick only once you have confirmed the data is really there'),
                booleanParam(name: 'OVERWRITE_UNREADABLE', defaultValue: false,
                        description: 'Only when inspect reports this key UNREADABLE. Overwrites a ' +
                                'value nothing can parse; against a readable one it changes ' +
                                'nothing -- monotonicity included, so a generation at or ahead of ' +
                                'this one is still kept'),
        ])
])

// Named, never assumed. The choice above constrains the form and nothing else: a build started
// through the API or by another job can carry a null or a misspelling, and a milestone only moves
// forward, so one published to the wrong key cannot be taken back.
Map work = PUBLISHES[params.WORK]
if (work == null) {
    error "piplex: WORK is '${params.WORK}', which this job does not publish for. It knows " +
          "${PUBLISHES.keySet()}"
}
String generation = params.GENERATION ?: ''
boolean confirmed = params.DATA_CONFIRMED ?: false
boolean overwriteUnreadable = params.OVERWRITE_UNREADABLE ?: false

// No node: none of the steps below need a workspace.
stage('Check') {
    if (!generation?.trim()) {
        error 'piplex: name the generation to announce'
    }
    if (!confirmed) {
        // A deliberate stop rather than a prompt. The mistake this job can make is not
        // recoverable: a milestone only moves forward, and consumers act on it at once.
        error 'piplex: confirm the data exists before announcing it. A milestone cannot be ' +
              'withdrawn, and consumers act on it as soon as it is published'
    }
}
stage('Announce') {
    String inForce = piplexPublish key: work.completedWhen, generation: generation,
                                   environment: ENVIRONMENT,
                                   overwriteUnreadable: overwriteUnreadable
    echo "piplex: '${work.completedWhen}' is at '${inForce}'; waiting consumers continue"
}
