// Take this controller out for maintenance, and put it back.
//
// Who this is for: whoever patches controllers. Routine, and narrower than stopping the work --
// other owners carry on throughout.
//
// What it is for. Rebooting a controller that is running guarded work kills the process holding the
// lease. The lease is then not released but left to expire, and until it does nobody picks the work
// up -- not even an owner designated in the meantime. Draining ends that run deliberately instead:
// the switch revokes it, Jenkins cancels the body so the pipeline's own post steps run, the lease
// goes back at once, and the wait below proves the machine is quiet before anybody touches it.
//
// It does NOT let the run finish. Tonight's round on this controller stops either way; the choice
// is between stopping it in the open and having it disappear with the lease still held.
//
// There is no choice of work here, and that is the point. The question being asked is about the
// machine -- it is being patched -- so everything running on it has to stop. A drain that took one
// round out of five would answer "safe to touch" when it is not.
//
// It reaches only work that names a switch. piplex-init refuses to leave that unsaid: work with no
// enabledBy is reported when the estate is written, because it is the one way a controller reported
// drained can still be running something.
//
// RUN IT ON THE CONTROLLER BEING TAKEN OUT. Whether work is still running is a question about
// processes on one machine, and only that machine can answer it. The step refuses to pretend
// otherwise for anybody else's owner id -- which is also why this job is generated per controller
// and carries no owner parameter.
//
// Generated by piplex-init from the estate description. The block below is the estate; everything
// under it is the procedure, and it is what the tests run. Regenerate rather than editing:
//
//   java -jar piplex-init.jar --from estate.properties
//
// See docs/09-deployment.md.

// ---- piplex-init: generated from the estate. Regenerate rather than editing it. ----
final String ENVIRONMENT = ''
final String OWNER_ID = ''
final List OWNERS = []
final String CREDENTIALS_ID = ''
final String CLIENT_ID = ''
final Map WORK = [:]
// ---- end piplex-init ----

// Ungenerated, this job knows neither which controller it is on nor which switches to write.
if (!ENVIRONMENT?.trim() || !OWNER_ID?.trim() || WORK.isEmpty()) {
    error 'piplex: this job has not been generated. It is the template piplex-init fills in from ' +
          'the estate description -- run that and install what it writes'
}

// Every switch the estate knows, because a drain covers all of them.
final List SWITCHES = []
WORK.each { name, work ->
    if (work.enabledBy && !SWITCHES.contains(work.enabledBy)) {
        SWITCHES.add(work.enabledBy)
    }
}
if (SWITCHES.isEmpty()) {
    error 'piplex: no work in this estate names a switch, so a drain would take nothing out and ' +
          'report this controller quiet. Name one in enabledBy and regenerate'
}

properties([
        parameters([
                choice(name: 'ACTION', choices: ['drain', 'restore'],
                        description: "Take ${OWNER_ID} out, or put it back"),
                string(name: 'DRAIN_TIMEOUT', defaultValue: '30m',
                        description: 'How long to wait for work running here to stop'),
                string(name: 'REASON', defaultValue: '',
                        description: 'Change or incident reference'),
                booleanParam(name: 'OVERWRITE_UNREADABLE', defaultValue: false,
                        description: 'Only when inspect reports a key UNREADABLE. Overwrites a ' +
                                'value nothing can parse; against a readable one it changes nothing'),
        ])
])

// Named, never assumed. The choice above constrains the form and nothing else: a build started
// through the API can carry a null or a misspelling, and anything that was not 'restore' used to
// mean drain.
String action = params.ACTION
if (!(action in ['drain', 'restore'])) {
    error "piplex: ACTION is '${action}'. It must be 'drain' or 'restore'; there is no default, " +
          'because the one it would have takes a controller out of service'
}
String drainTimeout = params.DRAIN_TIMEOUT ?: '30m'
String reason = params.REASON ?: ''
boolean overwriteUnreadable = params.OVERWRITE_UNREADABLE ?: false

// No node: a controller being drained may have no executor free, and draining it is precisely when
// that must not stop the job. None of the steps below need a workspace.
if (action == 'restore') {
    stage('Put back') {
        withPiplexOperator(credentialsId: CREDENTIALS_ID, clientId: CLIENT_ID,
                           environment: ENVIRONMENT) {
            for (String key : SWITCHES) {
                piplexSwitch key: key, enabled: true, ownerId: OWNER_ID, reason: reason,
                             overwriteUnreadable: overwriteUnreadable
            }
        }
        echo "piplex: '${OWNER_ID}' takes work again: ${SWITCHES.join(', ')}"
    }
    return
}

// Two passes, and the order is the whole of it. Writing a switch and waiting on it before writing
// the next leaves the work the next one guards free to start here throughout that wait -- so every
// switch goes off first, and only then is anything waited for. Writing a switch already in the state
// asked for changes nothing, so the second pass costs a read.
stage('Stop new work') {
    withPiplexOperator(credentialsId: CREDENTIALS_ID, clientId: CLIENT_ID,
                       environment: ENVIRONMENT) {
        for (String key : SWITCHES) {
            piplexSwitch key: key, enabled: false, ownerId: OWNER_ID, reason: reason,
                         overwriteUnreadable: overwriteUnreadable
        }
    }
    echo "piplex: nothing new starts on '${OWNER_ID}'. Waiting for what is already running"
}
stage('Wait for quiet') {
    // Each call returns only once nothing that switch governs is still running here, and fails if
    // that has not happened in time. A failure means the controller is NOT safe to touch. The waits
    // run one after another but overlap in effect: by the time the first returns, everything else
    // has had that long to stop too, since nothing new has been able to start since the pass above.
    withPiplexOperator(credentialsId: CREDENTIALS_ID, clientId: CLIENT_ID,
                       environment: ENVIRONMENT) {
        for (String key : SWITCHES) {
            piplexSwitch key: key, enabled: false, ownerId: OWNER_ID,
                         reason: reason, drainTimeout: drainTimeout,
                         overwriteUnreadable: overwriteUnreadable
        }
    }
    echo "piplex: '${OWNER_ID}' is drained and quiet; maintenance can start"
}
