// Move work to another owner.
//
// Who this is for: whoever decides where the work runs -- an incident, or a planned move between
// sites. Not the same people as the maintenance drain, which is why it is its own job.
//
// The choice is a piece of work, because a designation belongs to one. The four guards read by the
// confirmation below belong to the same one, and naming a guard from another piece of work would
// report on something nobody asked about -- so they are not typed here, they are looked up.
//
// Time matters. A candidate on the new owner takes over only while it is parked within its
// handoverWait; past that, the work waits for that owner's next scheduled build -- which for a
// nightly job means the round is not produced today.
//
// Generated by piplex-init from the estate description. The block below is the estate; everything
// under it is the procedure, and it is what the tests run. Regenerate rather than editing:
//
//   java -jar piplex-init.jar --from estate.properties
//
// Keep it in the folder holding the operations credential. See docs/09-deployment.md.

// ---- piplex-init: generated from the estate. Regenerate rather than editing it. ----
final String ENVIRONMENT = ''
final String OWNER_ID = ''
final List OWNERS = []
final String CREDENTIALS_ID = ''
final String CLIENT_ID = ''
final Map WORK = [:]
// ---- end piplex-init ----

// Ungenerated, this job knows neither the work nor the owners it could be moved between.
if (!ENVIRONMENT?.trim() || WORK.isEmpty() || OWNERS.isEmpty()) {
    error 'piplex: this job has not been generated. It is the template piplex-init fills in from ' +
          'the estate description -- run that and install what it writes'
}

// Only work piplex itself decides the owner of. Where somebody else's key says who runs, that key is
// the handover, and writing a designation beside it is refused.
final Map MOVABLE = [:]
WORK.each { name, work ->
    if (work.designatedBy) {
        MOVABLE[name] = work
    }
}
if (MOVABLE.isEmpty()) {
    error 'piplex: no work in this estate names a designation, so piplex does not decide where it ' +
          'runs and this job has nothing to move. An estate on an active key fails over instead'
}

properties([
        parameters([
                choice(name: 'WORK', choices: MOVABLE.keySet() as List,
                        description: 'Which work moves. Its designation key and its guards follow'),
                choice(name: 'NEW_OWNER', choices: OWNERS,
                        description: 'The controller that should hold the work'),
                string(name: 'GENERATION', defaultValue: '',
                        description: 'The round being moved, if one is. Empty reads the milestone ' +
                                'without judging it'),
                string(name: 'REASON', defaultValue: '',
                        description: 'Change or incident reference. The only account piplex keeps'),
                booleanParam(name: 'OVERWRITE_UNREADABLE', defaultValue: false,
                        description: 'Only when inspect reports this key UNREADABLE. Overwrites a ' +
                                'value nothing can parse; against a readable one it changes nothing'),
        ])
])

// Named, never assumed. The choices above constrain the form and nothing else: a build started
// through the API or by another job can carry a null or a misspelling.
Map work = MOVABLE[params.WORK]
if (work == null) {
    error "piplex: WORK is '${params.WORK}', which this job cannot move. It knows ${MOVABLE.keySet()}"
}
String newOwner = params.NEW_OWNER
if (!OWNERS.contains(newOwner)) {
    error "piplex: NEW_OWNER is '${newOwner}', which is no controller in this estate. Sending work " +
          "to an owner that does not exist parks every candidate until its wait runs out. It knows " +
          "${OWNERS}"
}
String generation = params.GENERATION ?: ''
String reason = params.REASON ?: ''
boolean overwriteUnreadable = params.OVERWRITE_UNREADABLE ?: false

// No node: a handover is done when a controller is in trouble, which is when an executor is least
// likely to be free. None of the steps below need a workspace.
stage('Hand over') {
    withPiplexOperator(credentialsId: CREDENTIALS_ID, clientId: CLIENT_ID,
                       environment: ENVIRONMENT) {
        String owner = piplexDesignate key: work.designatedBy, owner: newOwner, reason: reason,
                                       overwriteUnreadable: overwriteUnreadable
        echo "piplex: '${work.designatedBy}' now designates '${owner}'"
    }
}
stage('Confirm') {
    // The designation is only half the answer: what matters is whether the work can now run where it
    // was just sent. Every guard the work consults is read, from the one place they are written
    // down -- a guard left out is one this step silently skips, and a handover to a controller that
    // is drained, or to work that is switched off everywhere, would then be reported as confirmed.
    //
    // No activeWhenKey: a designation and an active key are two answers to who runs, and a request
    // may not name both. MOVABLE holds only work that has a designation.
    String blocking = piplexInspect key: work.key, environment: ENVIRONMENT,
                                    ownerId: newOwner, designatedBy: work.designatedBy,
                                    enabledBy: work.enabledBy ?: '',
                                    completedWhen: work.completedWhen ?: '',
                                    generation: generation
    if (blocking) {
        // Not green. The designation landed, and the work still cannot run where it was sent -- which
        // is the half somebody reading a build result at two in the morning has to be told.
        currentBuild.result = 'UNSTABLE'
        echo "piplex: the new owner is still blocked: ${blocking}"
    } else {
        echo "piplex: nothing readable is stopping '${work.key}' at '${newOwner}'"
    }
}
