// Why has tonight's round not run?
//
// Who this is for: everyone. Reading grants nobody anything, so this job needs no operations
// credential and no operator block, and every controller can read its own guards under every trust
// profile.
//
// Generated by piplex-init from the estate description. The block below is the estate; everything
// under it is the procedure, and it is what the tests run. Regenerate rather than editing:
//
//   java -jar piplex-init.jar --from estate.properties
//
// See docs/09-deployment.md.

// ---- piplex-init: generated from the estate. Regenerate rather than editing it. ----
final String ENVIRONMENT = ''
final String OWNER_ID = ''
final List OWNERS = []
final String CREDENTIALS_ID = ''
final String CLIENT_ID = ''
final Map WORK = [:]
// ---- end piplex-init ----

// Ungenerated, this job knows no keys at all, and a job that guesses one reads somebody else's.
if (!ENVIRONMENT?.trim() || WORK.isEmpty()) {
    error 'piplex: this job has not been generated. It is the template piplex-init fills in from ' +
          'the estate description -- run that and install what it writes'
}

properties([
        parameters([
                choice(name: 'WORK', choices: WORK.keySet() as List,
                        description: 'Which work this is about. Every guard it names is read'),
                string(name: 'OWNER_ID', defaultValue: '',
                        description: 'The owner being asked about. Empty means this controller'),
                string(name: 'GENERATION', defaultValue: '',
                        description: 'The round being asked about, usually the business date'),
        ])
])

// Named, never assumed. The choice above constrains the form and nothing else: a build started
// through the API or by another job can carry a null or a misspelling.
Map work = WORK[params.WORK]
if (work == null) {
    error "piplex: WORK is '${params.WORK}', which this job does not define. It knows ${WORK.keySet()}"
}

// No node: a diagnosis is most needed when a controller has no executor free, and none of
// the steps below need a workspace.
stage('Inspect') {
    // Every guard the work names, from the one place they are written down. A guard left out is one
    // this step cannot read, and it answers with what it was given.
    String blocking = piplexInspect key: work.key,
                                    environment: ENVIRONMENT,
                                    ownerId: params.OWNER_ID ?: '',
                                    designatedBy: work.designatedBy ?: '',
                                    enabledBy: work.enabledBy ?: '',
                                    completedWhen: work.completedWhen ?: '',
                                    generation: params.GENERATION ?: '',
                                    activeWhenKey: work.activeKey ?: '',
                                    activeWhenValue: work.activeKey ? (params.OWNER_ID ?: OWNER_ID) : ''
    // Not failed when something is blocking: "the work is switched off" is an answer, not a
    // fault, and a red build would say the diagnosis went wrong rather than what it found.
    currentBuild.description = blocking ?: 'nothing readable is stopping it'
}
