// Stop the work everywhere, and resume it.
//
// Who this is for: whoever is entitled to halt a business process -- bad input data, a defect found,
// an instruction from outside. This is the widest blast radius of anything here: every owner stops.
//
// It is deliberately NOT the maintenance drain. Draining one controller is routine; this is not, and
// keeping them as separate jobs is how "may patch a controller" stays separate from "may stop the
// nightly run".
//
// The choice is a switch rather than a piece of work, because a switch is the unit somebody decides
// to stop: where two rounds share one, stopping it stops both, and that is what it was made to mean.
//
// Generated by piplex-init from the estate description. The block below is the estate; everything
// under it is the procedure, and it is what the tests run. Regenerate rather than editing:
//
//   java -jar piplex-init.jar --from estate.properties
//
// See docs/09-deployment.md.

// ---- piplex-init: generated from the estate. Regenerate rather than editing it. ----
final String ENVIRONMENT = ''
final String OWNER_ID = ''
final List OWNERS = []
final String CREDENTIALS_ID = ''
final String CLIENT_ID = ''
final Map WORK = [:]
// ---- end piplex-init ----

// Ungenerated, this job knows no keys at all, and a job that guesses one halts somebody else's work.
if (!ENVIRONMENT?.trim() || WORK.isEmpty()) {
    error 'piplex: this job has not been generated. It is the template piplex-init fills in from ' +
          'the estate description -- run that and install what it writes'
}

// What each switch governs, so the operator chooses a business process rather than a key. Work that
// names no switch cannot be stopped at all, and piplex-init says so when the estate is written.
final Map GOVERNS = [:]
WORK.each { name, work ->
    if (work.enabledBy) {
        if (!GOVERNS.containsKey(work.enabledBy)) {
            GOVERNS[work.enabledBy] = []
        }
        GOVERNS[work.enabledBy].add(name)
    }
}
if (GOVERNS.isEmpty()) {
    error 'piplex: no work in this estate names a switch, so there is nothing this job can stop. ' +
          'Name one in enabledBy and regenerate'
}

properties([
        parameters([
                choice(name: 'ACTION', choices: ['stop', 'resume'],
                        description: 'Halt the work everywhere, or let it run again'),
                choice(name: 'SWITCH_KEY', choices: GOVERNS.keySet() as List,
                        description: 'The switch to write. It governs: ' +
                                GOVERNS.collect { key, work -> "${key} -> ${work.join(', ')}" }
                                        .join(' | ')),
                string(name: 'REASON', defaultValue: '',
                        description: 'Change or incident reference. The only account piplex keeps'),
                booleanParam(name: 'OVERWRITE_UNREADABLE', defaultValue: false,
                        description: 'Only when inspect reports this key UNREADABLE. Overwrites a ' +
                                'value nothing can parse; against a readable one it changes nothing'),
        ])
])

// Named, never assumed. The choices above constrain the form and nothing else: a build started
// through the API or by another job can carry a null or a misspelt 'Resume', and anything that was
// not 'resume' used to mean stop the work everywhere.
String action = params.ACTION
if (!(action in ['stop', 'resume'])) {
    error "piplex: ACTION is '${action}'. It must be 'stop' or 'resume'; it is not guessed, because " +
          'the value it would be guessed as is the one that halts the work on every controller'
}
boolean stopping = action == 'stop'
String switchKey = params.SWITCH_KEY
if (!GOVERNS.containsKey(switchKey)) {
    error "piplex: SWITCH_KEY is '${switchKey}', which no work in this estate consults. A switch " +
          "nothing reads halts nothing. This job knows ${GOVERNS.keySet()}"
}
String reason = params.REASON ?: ''
boolean overwriteUnreadable = params.OVERWRITE_UNREADABLE ?: false

// No node: this job writes one key and must run when no executor is free, which is exactly the state
// a controller in trouble is in. None of the steps below need a workspace.
stage(stopping ? 'Stop everywhere' : 'Resume') {
    withPiplexOperator(credentialsId: CREDENTIALS_ID, clientId: CLIENT_ID,
                       environment: ENVIRONMENT) {
        // No ownerId: the shared switch. Runs in flight stop, new ones skip, nobody takes over.
        piplexSwitch key: switchKey, enabled: !stopping, reason: reason,
                     overwriteUnreadable: overwriteUnreadable
    }
    String governed = GOVERNS[switchKey].join(', ')
    echo stopping
            ? "piplex: '${switchKey}' is off. Nothing it guards runs anywhere: ${governed}"
            : "piplex: '${switchKey}' is on for ${governed}. Whether the missed round is caught up " +
              'is your call'
}
