/*
 * Copyright (c) 2026 Anatoly Gudkov and others.
 *
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for details.
 */

package io.github.green4j.piplex.init;

import io.github.green4j.piplex.init.Estate.Controller;
import io.github.green4j.piplex.init.Estate.Transport;

/**
 * One controller's piplex settings, as Configuration as Code reads them.
 *
 * <p>Generated per controller because two of the fields are what tell the controllers apart: the
 * owner id designations point at, and the client id the ACL grants. An estate where those were
 * copied between machines has two controllers answering to one name, which is the failure the
 * settings page cannot see and {@link Estate#problems()} refuses.
 *
 * <p>No secret is ever written here. Every pass phrase and token is a CasC variable, and the key
 * material is named by the path it lives at: this file is generated, and a generated file is
 * committed somewhere.
 */
public final class Casc {

    private Casc() {
    }

    /**
     * @param estate     what was decided
     * @param controller the controller this configuration is for
     * @return the contents of a {@code jenkins.yaml}, or of one piece of it
     */
    public static String render(final Estate estate, final Controller controller) {
        final StringBuilder text = new StringBuilder();
        header(text, estate, controller);
        text.append("unclassified:\n  piplex:\n");
        field(text, "ownerId", controller.ownerId());
        field(text, "clientId", controller.clientId());
        // Named, never left to default: a controller whose default environment is wrong writes
        // every key of another set of orchestrations, and nothing says so at the time.
        field(text, "environment", estate.environment().value());
        field(text, "nodes", estate.nodes());
        transport(text, estate, controller);
        return text.toString();
    }

    private static void transport(final StringBuilder text, final Estate estate,
                                  final Controller controller) {
        if (estate.transport() == Transport.ALLOWALL) {
            return;
        }
        text.append("    tls: true\n");
        // The node has to be one of the nodes above, or a certificate signed by the same authority
        // is enough to be the cluster.
        text.append("    tlsVerifyNodeIdentity: true\n");
        field(text, "tlsTruststore", estate.truststore());
        field(text, "tlsTruststorePassword", "${PIPLEX_TRUSTSTORE_PASSWORD}");
        if (estate.transport() == Transport.TOKEN) {
            field(text, "token", "${PIPLEX_TOKEN}");
            return;
        }
        // mTLS: the certificate's CN is the client id, and the plugin refuses a block whose
        // certificate names somebody else.
        field(text, "tlsKeystore", estate.keystore(controller));
        field(text, "tlsKeystorePassword", "${PIPLEX_KEYSTORE_PASSWORD}");
    }

    private static void field(final StringBuilder text, final String name, final String value) {
        text.append("    ").append(name).append(": \"").append(escaped(value)).append("\"\n");
    }

    private static String escaped(final String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static void header(final StringBuilder text, final Estate estate,
                               final Controller controller) {
        text.append("# piplex on '").append(controller.ownerId())
                .append("', generated by piplex-init. Regenerate rather than editing it.\n");
        switch (estate.transport()) {
            case ALLOWALL -> text.append(
                    "#\n# This cluster admits any client that can reach it, so nothing here proves "
                    + "who this\n# controller is. Right on a trusted network and nowhere else; see "
                    + "docs/07-discas.md.\n");
            case TOKEN -> text.append(
                    "#\n# PIPLEX_TOKEN and PIPLEX_TRUSTSTORE_PASSWORD are resolved by Configuration "
                    + "as Code from\n# the environment or a secrets directory. They are named here "
                    + "and stored elsewhere: this\n# file is generated, and a generated file ends up "
                    + "in a repository.\n");
            case MTLS -> text.append(
                    "#\n# The client certificate at the path below must have '")
                    .append(controller.clientId())
                    .append("' as its CN: that is\n# the name the ACL grants, and the plugin refuses "
                    + "an operator block whose certificate names\n# somebody else. The pass phrases "
                    + "are CasC variables, resolved from the environment or a\n# secrets directory, "
                    + "and are not written here.\n");
            default -> throw new IllegalStateException("Unknown transport " + estate.transport());
        }
        text.append("#\n# See docs/05-jenkins.md#controller-configuration\n\n");
    }
}
