/*
 * Copyright (c) 2026 Anatoly Gudkov and others.
 *
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for details.
 */

package io.github.green4j.piplex.init;

import io.github.green4j.piplex.init.Estate.Controller;
import io.github.green4j.piplex.init.Estate.Transport;
import io.github.green4j.piplex.init.Estate.Work;

/**
 * What to do with what was just written, in the order to do it.
 *
 * <p>Generating four kinds of file and leaving somebody to work out which goes where is most of the
 * work still undone. This is the other half: the files named, the one command each needs, and the
 * two things nothing here can do for anybody -- put the key material in place, and check it on a
 * day when nothing is wrong.
 */
public final class RunNotes {

    /** The file this is written to. */
    public static final String FILE = "RUN.md";

    private RunNotes() {
    }

    /**
     * @param estate what was decided
     * @return the notes, as Markdown
     */
    public static String render(final Estate estate) {
        final StringBuilder text = new StringBuilder();
        text.append("## Installing the '").append(estate.environment().value())
                .append("' estate\n\n");
        text.append("Generated by piplex-init from `").append(Estates.FILE)
                .append("`. Change that file and run the tool\nagain rather than editing anything "
                        + "here: the keys in the ACL, the guards in the pipeline and\nthe names in "
                        + "the operator jobs are one set, and they stay one set by being written "
                        + "together.\n\n");
        secrets(text, estate);
        cluster(text, estate);
        controllers(text, estate);
        pipelines(text, estate);
        check(text, estate);
        return text.toString();
    }

    private static void secrets(final StringBuilder text, final Estate estate) {
        if (estate.transport() == Transport.ALLOWALL) {
            text.append("### 1. Nothing to prepare\n\n"
                    + "This estate reaches the cluster over a trusted network: no token, no TLS, "
                    + "and a client id\nis a claim rather than a proof. Right while the client port "
                    + "is reachable only from the\ncontrollers, and wrong the moment it is not. See "
                    + "`docs/07-discas.md`.\n\n");
            return;
        }
        text.append("### 1. Put the key material in place\n\n");
        text.append("Nothing generated here contains a secret, and nothing here can make one for "
                + "you: a key\nwritten by a tool that also writes files into a repository is a key "
                + "in a repository. What\nthe generated configuration does is name where each file "
                + "lives and which variable carries\nits pass phrase.\n\n");
        text.append("On every controller, under `").append(estate.secretsDir()).append("`:\n\n");
        text.append("| File | What it is |\n|---|---|\n");
        text.append("| `discas-trust.p12` | The authority that signed the cluster's client-port "
                + "certificates |\n");
        if (estate.transport() == Transport.MTLS) {
            for (final Controller controller : estate.controllers()) {
                text.append("| `").append(controller.clientId())
                        .append(".p12` | That controller's own certificate, CN `")
                        .append(controller.clientId()).append("` |\n");
            }
        }
        text.append('\n');
        if (estate.transport() == Transport.TOKEN) {
            text.append("And the shared secret in `PIPLEX_TOKEN`, with the trust store's pass "
                    + "phrase in\n`PIPLEX_TRUSTSTORE_PASSWORD`. Configuration as Code resolves "
                    + "both; neither is in the YAML.\n\n");
            text.append("If you have no trust store yet, it holds the certificate authority the "
                    + "cluster's client\nport was configured with -- the one behind "
                    + "`--client-tls-keystore`:\n\n");
            text.append("```bash\nkeytool -importcert -noprompt -alias discas-client-ca \\\n"
                    + "        -file client-ca.crt \\\n"
                    + "        -keystore discas-trust.p12 -storetype PKCS12 "
                    + "-storepass \"$PIPLEX_TRUSTSTORE_PASSWORD\"\n```\n\n");
            return;
        }
        text.append("The pass phrases go in `PIPLEX_TRUSTSTORE_PASSWORD` and "
                + "`PIPLEX_KEYSTORE_PASSWORD`, which\nConfiguration as Code resolves. Neither is "
                + "in the YAML.\n\n");
        text.append("**The CN is not decoration.** Under mTLS the certificate's CN *is* the client "
                + "id: it is what\nthe ACL grants, and the plugin refuses an operator block whose "
                + "certificate names somebody\nelse. If you have no certificates yet, ask whoever "
                + "holds the client-port authority for one\nper name above. A request looks like "
                + "this:\n\n");
        text.append("```bash\n");
        for (final Controller controller : estate.controllers()) {
            text.append("keytool -genkeypair -alias ").append(controller.clientId())
                    .append(" -keyalg RSA -keysize 3072 \\\n")
                    .append("        -dname \"CN=").append(controller.clientId()).append("\" \\\n")
                    .append("        -keystore ").append(controller.clientId())
                    .append(".p12 -storetype PKCS12 -storepass \"$PIPLEX_KEYSTORE_PASSWORD\"\n");
            text.append("keytool -certreq -alias ").append(controller.clientId())
                    .append(" -keystore ").append(controller.clientId())
                    .append(".p12 -storepass \"$PIPLEX_KEYSTORE_PASSWORD\" \\\n")
                    .append("        -file ").append(controller.clientId()).append(".csr\n");
        }
        text.append("```\n\nSend each `.csr` to that authority, and import the signed certificate "
                + "back into the same\n`.p12` under the same alias, together with the authority's "
                + "own certificate.\n\n");
    }

    private static void cluster(final StringBuilder text, final Estate estate) {
        text.append("### 2. Give the cluster its ACL\n\n");
        text.append("`acl/piplex.conf` grants exactly the keys this estate writes, composed by the "
                + "same code that\nwrites them. Point every node at it and reload:\n\n");
        text.append("```bash\nscp acl/piplex.conf node:/etc/discas/acl.conf\n"
                + "curl -X POST http://node:7102/reload\n```\n\n");
        if (estate.grants() == Estate.Grants.PER_KEY) {
            text.append("Granted key by key, so each controller may write only the work it runs. "
                    + "Every piece of work\nadded later is a regeneration and another reload; a "
                    + "grant left out fails that work closed.\n\n");
        } else {
            text.append("Granted per environment: one line each, no upkeep, and no separation "
                    + "within it.\n\n");
        }
    }

    private static void controllers(final StringBuilder text, final Estate estate) {
        text.append("### 3. Configure the controllers and install the jobs\n\n");
        text.append("One directory per controller, because the two fields that tell controllers "
                + "apart are in\nthem. Copied between machines, two controllers answer to one name "
                + "and which of them runs the\nwork is chance.\n\n");
        for (final Controller controller : estate.controllers()) {
            text.append("- **").append(controller.ownerId()).append("** -- `controllers/")
                    .append(controller.ownerId())
                    .append("/jenkins.yaml` into its Configuration as Code, and\n  `controllers/")
                    .append(controller.ownerId()).append("/jobs/` as five pipeline jobs.\n");
        }
        text.append("\nKeep the five jobs in one folder. They are separate jobs because Jenkins "
                + "grants rights per\njob, and \"may patch a controller\" and \"may stop tonight's "
                + "run\" are not the same right.\n\n");
        if (estate.operator().apart()) {
            text.append("The operations credential `").append(estate.operator().credentialsId())
                    .append("` goes in **that folder's** store, not the\nglobal one. "
                            + "`drain-controller` is generated without it on purpose: a controller "
                            + "takes itself\nout under its own identity, or the credential ends up "
                            + "on every controller and separating it\nbought nothing.\n\n");
        }
        text.append("Then run one build that reaches the store. The settings page does not test "
                + "connectivity, and a\nwrong port or a version mismatch shows up here rather than "
                + "at two in the morning.\n\n");
    }

    private static void pipelines(final StringBuilder text, final Estate estate) {
        text.append("### 4. Guard the work\n\n");
        text.append("`pipelines/` holds one block per piece of work. These are **not** files to "
                + "install: the\npipelines belong to whoever wrote them, and are very often "
                + "generated from templates of their\nown. Paste each block into its pipeline, or "
                + "feed it to whatever generates them.\n\n");
        for (final Work work : estate.work()) {
            text.append("- `pipelines/").append(work.key()).append(".groovy` -- for **")
                    .append(work.key()).append("**");
            if (work.follows()) {
                text.append(", and `activeWhenValue` differs per controller: it is the owner id of "
                        + "the\n  controller the pipeline is running on");
            }
            text.append(".\n");
        }
        text.append("\n");
    }

    private static void check(final StringBuilder text, final Estate estate) {
        text.append("### 5. Check it before you need it\n\n");
        text.append("In order, and on a day when nothing is wrong.\n\n");
        text.append("1. Run `inspect`. It should describe the work truthfully.\n");
        text.append("2. Run `stop-work` with `stop`, confirm a guarded build skips, then "
                + "`resume`.\n");
        text.append("3. Run `drain-controller` on one controller while work is running there. It "
                + "must wait, not\n   return at once.\n");
        if (estate.work().stream().anyMatch(Work::designated)) {
            text.append("4. Run `handover` to another controller and back. A yellow build means "
                    + "the designation\n   landed and the work still cannot run there.\n");
        }
        if (estate.operator().apart()) {
            text.append("5. Run an operator job from a job **outside** the credential's folder. It "
                    + "must fail: that\n   failure is the access control working.\n");
        }
        text.append("\nThe standing version of this is `docs/07-discas.md#production-checklist`.\n");
    }
}
